<div class="row">
<?php if ($this->error): ?>
<p class="error">
    There were one or more isues with your submission. Please correct them as 
    indicated below.
</p>
<?php endif ?>
<?php 
	$form = $this->form;
	$form->prepare();
	$form->setAttribute('action', $this->url(NULL, array('controller'=>'Admin', 'action' => 'login')));
	$form->setAttribute('method', 'post');

?>
    <div class="col-md-4  login-form">
        <div class="panel panel-default">
        	<div class="panel-heading">
                <h3>Admin</h3>
            </div>
            <div class="panel-body">
              	<table>
              	<?= $this->form()->openTag($form);?>
              	<tr>
              		<td>
              			<?=$this->formLabel($form->get('email'));?>
              		</td>
              		<td>
              			<?=$this->formElement($form->get('email'));?>	
              		</td>
					<td>
					<?=$this->formElementErrors($form->get('email'));?>
					</td>
              	</tr>
              	<tr>
              		<td>
              			<?=$this->formLabel($form->get('password'));?>
              		</td>
              		<td>
              			<?=$this->formElement($form->get('password'));?>
              		</td>
					<td>
						<?=$this->formElementErrors($form->get('password'));?>
					</td>
              	</tr>
				<tr>
					<td rowspan=3>
              			<div class="login-submit">
              			 <?=$this->formElement($form->get('submit'));?>
	    				</div>
              		</td>
				</tr>
              	<?=$this->form()->closeTag() ?>
              	</table>
            </div>
             <div class="flashMessages">
				<?php 
					foreach($this->flashMessenger()->getMessages() as $message) { 
					     echo $message;
					} 
			     ?>
		    </div>
        </div>
    </div>

</div>
